swagger: "2.0"
info:
  title: Bank Argent Transactions API
  description: API endpoints for managing transactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Get User Accounts
      description: API to fetch all accounts of the authenticated user
      produces:
        - application/json
      responses:
        "200":
          description: Accounts retrieved successfully
          schema:
            $ref: "#/definitions/AccountsResponse"
        "400":
          description: Invalid request
        "500":
          description: Internal server error

  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Get Transactions for the Current Month
      description: API to fetch all transactions for the current month for a given account
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: ID of the account to retrieve transactions for
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid request
        "500":
          description: Internal server error

  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get Transaction Details
      description: API to fetch details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to retrieve
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid transaction ID
        "404":
          description: Transaction not found
        "500":
          description: Internal server error

    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction
      description: API to update category and notes of a specific transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to update
        - in: body
          name: body
          description: Update payload
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid request
        "404":
          description: Transaction not found
        "500":
          description: Internal server error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Account:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the account
      name:
        type: string
        description: Name of the account
      balance:
        type: number
        format: float
        description: Current balance of the account
      lastFour:
        type: string
        description: Last four digits of the account number
      balanceType:
        type: string
        description: Type of balance

  AccountsResponse:
    type: object
    properties:
      accounts:
        type: array
        items:
          $ref: "#/definitions/Account"

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      accountId:
        type: string
        description: ID of the account associated with the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      balance:
        type: number
        format: float
        description: Account balance after the transaction
      type:
        type: string
        description: Type of the transaction (e.g., electronic)
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes associated with the transaction

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Updated category of the transaction
      notes:
        type: string
        description: Updated notes associated with the transaction

  TransactionsResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
